apiVersion: apps/v1
kind: Deployment
metadata:
  name: fomantis-app-deployment
  labels:
    app: fomantis-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fomantis-app-deployment
  template:
    metadata:
      labels:
        app: fomantis-app-deployment
    spec:
      containers:
       - name: fomantis-app-deployment
         image: travisfrels/fomantis-app:latest
         ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: fomantis-app-service
spec:
  selector:
    app: fomantis-app-deployment
  ports:
   - protocol: TCP
     port: 3000
     targetPort: 3000
  type: LoadBalancer
