apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: analyze-sentiment-service
spec:
  template:
    spec:
      containers:
        - image: travisfrels/analyze-sentiment:latest
          ports:
            - containerPort: 8080
