apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: persist-comment-service
spec:
  template:
    spec:
      containers:
        - image: travisfrels/persist-comment:latest
          ports:
            - containerPort: 8080
