apiVersion: apps/v1
kind: Deployment
metadata:
  name: fomantis-api-deployment
  labels:
    app: fomantis-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fomantis-api-deployment
  template:
    metadata:
      labels:
        app: fomantis-api-deployment
    spec:
      containers:
        - name: fomantis-api-deployment
          image: travisfrels/fomantis-api:latest
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: fomantis-api-service
spec:
  selector:
    app: fomantis-api-deployment
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: LoadBalancer
---
apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  name: fomantis-api-sinkbinding
spec:
  subject:
    apiVersion: apps/v1
    kind: Deployment
    selector:
      matchLabels:
        app: fomantis-api-deployment
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: fomantis-broker
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: comment-persisted-trigger
spec:
  broker: fomantis-broker
  filter:
    attributes:
      type: comment-persisted
  subscriber:
    uri: http://fomantis-api-service.default.svc.cluster.local:3001/comment-persisted
